# Generated by Django 5.1.7 on 2025-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='arrival_time',
            new_name='departure_date',
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
