# Generated by Django 5.1.7 on 2025-04-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_arrival_time_bus_departure_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
