# Generated by Django 5.1.7 on 2025-04-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_bus_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bus_status',
            field=models.CharField(default='Active', max_length=32),
        ),
    ]
