# Generated by Django 5.1.7 on 2025-04-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_bus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
